server:
  port: 8080

# DataSource Config
spring:
  application:
    name: test
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/${spring.application.name}
    username: sa
    password: sa
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      mode: always
  h2:
    console:
      enabled: true
      path: /h2
